version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: yarn debug
    ports:
      - 3000:3000
      - 9229:9229
    tty: true
    volumes:
      - ./src:/app/src
